### ISSUE TITLE
Serious Question

### ISSUE THREAD

**Issue by revelation-project** [ReyDonovan/LegionLegacy#2]
**Description:**

Hello Sir, why are you sharing the uwow leak? What is wrong with you? Never heard of licences?

**Current behaviour:**

You may have removed most of their copyright, but what you share is mostly consitent of uwow.biz code.

**Expected behaviour:**

You should delete your repo 

**Project(s): <-- Mandatory**

- [x] Issue found in ReyDonovan

**TC rev. hash/commit:** 

Oh well...

**Database version**

Yeah, right ...

**Operating system:** Whatever OS

**Comment by ReyDonovan** [comment]
all under the license)))
ManGosd
TrinityCore

it is a training project and cannot be used as a private server

**Comment by cooler-SAI** [comment]
and cannot have a Price!! Conan sell it 500$

**Comment by revelation-project** [comment]
I see that your understanding in the english language is by far limited.
Let me be more specific :

I assume you have heard of GPL3.0 at this point.

Im talking about that you **publicy share code from other people without permission.**

Let me point you to some points to make it clear what i am talking about :

Look here :
https://github.com/ReyDonovan/LegionLegacy/blob/23107b1647dffe10779f866921499829e000ee89/src/server/newscripts/Draenor/shadowmoon_valley.cpp#L2

or here :
https://github.com/ReyDonovan/LegionLegacy/blob/23107b1647dffe10779f866921499829e000ee89/src/server/game/Handlers/CommentatorHandler.cpp#L2

or here : 
https://github.com/ReyDonovan/LegionLegacy/blob/23107b1647dffe10779f866921499829e000ee89/src/server/game/Battlegrounds/Bracket.h#L2

"your" whole repo is full of that. Smells like DMCA.

**Comment by ReyDonovan** [comment]
LegionLegacy/src/server/newscripts/Draenor/shadowmoon_valley.cpp origin FireStorm))

**Comment by cooler-SAI** [comment]
I can add my copyrights right now!! it's not be mine anyway!! code PUBLIC!! they just added a line of this shit   * Copyright (C)   2013    uWoW <http://uwow.biz>
